create or replace view MATCH_DATA as
select CAST(TRIM(ladder) as CHAR) as ladder,
	   CAST(Match_ID as UNSIGNED) as Match_ID,
	   STR_TO_DATE(Match_date,'%m/%d/%Y') as Match_date,
	   STR_TO_DATE(CONCAT(Match_date, ' ',Match_time),'%m/%d/%Y %H:%i') as Match_time,
	   CAST(Match_rating as UNSIGNED) as Match_rating,
	   CAST(TRIM(Match_map) as CHAR) as Match_map,
	   TIME_TO_SEC(Match_length) as Match_length,
	   CAST(Match_player_no as UNSIGNED) as Match_player_no,
	   CAST(TRIM(Match_mod) as CHAR) as Match_mod,
	   CAST(TRIM(Player) as CHAR) as Player,
	   CAST(New_Rating as UNSIGNED) as New_Rating,
	   CAST(Points as SIGNED) as Points,
	   CAST(Team as UNSIGNED) as Team,
	   CAST(Civilization as CHAR) as Civilization,
	   CAST(Victory as BINARY) as Victory,
	   CAST(REPLACE(Military_Score,",","") as UNSIGNED) as Military_Score,
	   CAST(REPLACE(Economy_Score,",","")  as UNSIGNED) as Economy_Score,
	   CAST(REPLACE(Technology_Score,",","") as UNSIGNED) as Technology_Score,
	   CAST(REPLACE(Society_Score,",","") as UNSIGNED) as Society_Score,
	   CAST(REPLACE(Total_Score,",","") as UNSIGNED) as Total_Score,
	   CAST(REPLACE(Units_Killed,",","") as UNSIGNED) as Units_Killed,
	   CAST(REPLACE(Units_Lost,",","") as UNSIGNED) as Units_Lost,
	   CAST(REPLACE(Buildings_Razed,",","") as UNSIGNED) as Buildings_Razed,
	   CAST(REPLACE(Buildings_Lost,",","") as UNSIGNED) as Buildings_Lost,
	   CAST(REPLACE(Units_Converted,",","") as UNSIGNED) as Units_Converted,
	   CAST(REPLACE(Food,",","") as UNSIGNED) as Food,
	   CAST(REPLACE(Wood,",","") as UNSIGNED) as Wood,
	   CAST(REPLACE(Stone,",","") as UNSIGNED) as Stone,
	   CAST(REPLACE(Gold,",","") as UNSIGNED) as Gold,
	   CAST(REPLACE(Trade_Profit,",","") as UNSIGNED) as Trade_Profit,
	   CAST(REPLACE(Tribute_Received,",","") as UNSIGNED) as Tribute_Received,
	   CAST(REPLACE(Tribute_Sent,",","") as UNSIGNED) as Tribute_Sent,
	   CASE WHEN TRIM(Feudal_Time) = "n/a" THEN NULL ELSE TIME_TO_SEC(Feudal_Time) END as Feudal_Time, 
	   CASE WHEN TRIM(Castle_Time) = "n/a" THEN NULL ELSE TIME_TO_SEC(Castle_Time) END as Castle_Time, 
	   CASE WHEN TRIM(Imperial_Time) = "n/a" THEN NULL ELSE TIME_TO_SEC(Imperial_Time) END as Imperial_Time,
	   CAST(REPLACE(Research_Percent,'%','') as UNSIGNED)/100 as Research_Percent,
	   CAST(REPLACE(Total_Wonders,",","") as UNSIGNED) as Total_Wonders,
	   CAST(REPLACE(Total_Castles,",","") as UNSIGNED) as Total_Castles,
	   CAST(REPLACE(Relics_Captured,",","") as UNSIGNED) as Relics_Captured,
	   CAST(REPLACE(Relic_Gold,",","") as UNSIGNED) as Relic_Gold,
	   CAST(REPLACE(Villager_High,",","") as UNSIGNED) as Villager_High
from RAW_MATCH_DATA rmd 