
CREATE VIEW dbo.[MATCH_DATA] AS
SELECT [ladder]
      ,CAST([Match_ID] AS INT) AS [Match_ID]
      ,TRY_CONVERT(DATE,[Match_date]) AS [Match_date]
      ,TRY_CONVERT(TIME(0),[Match_time], 105) AS [Match_time]
      ,CAST([Match_rating] AS INT) AS [Match_rating]
      ,[Match_map]
      ,CASE WHEN [Match_length] LIKE '%:%' THEN LTRIM(DATEDIFF(MINUTE, 0, TRY_CONVERT(TIME(0),[Match_length], 105))) ELSE NULL END [Match_length]
      ,CAST([Match_player_no] AS INT) AS [Match_player_no]
      ,[Match_mod]
      ,[Player]
      ,CAST([New_Rating] AS INT) AS [New_Rating]
      ,CAST([Points] AS INT) AS [Points]
      ,CAST([Team] AS INT) AS [Team]
      ,[Civilization]
      ,CAST([Victory] AS INT) AS [Victory]
      ,CAST(REPLACE([Military_Score],',','') AS INT) AS [Military_Score]
	  ,CAST(REPLACE([Economy_Score],',','') AS INT) AS [Economy_Score]
	  ,CAST(REPLACE([Technology_Score],',','') AS INT) AS [Technology_Score]
	  ,CAST(REPLACE([Society_Score],',','') AS INT) AS [Society_Score]
	  ,CAST(REPLACE([Total_Score],',','') AS INT) AS [Total_Score]
	  ,CAST(REPLACE([Units_Killed],',','') AS INT) AS [Units_Killed]
	  ,CAST(REPLACE([Units_Lost],',','') AS INT) AS [Units_Lost]
	  ,CAST(REPLACE([Buildings_Razed],',','') AS INT) AS [Buildings_Razed]
	  ,CAST(REPLACE([Buildings_Lost],',','') AS INT) AS [Buildings_Lost]
	  ,CAST(REPLACE([Units_Converted],',','') AS INT) AS [Units_Converted]
	  ,CAST(REPLACE([Food],',','') AS INT) AS [Food]
	  ,CAST(REPLACE([Wood],',','') AS INT) AS [Wood]
	  ,CAST(REPLACE([Stone],',','') AS INT) AS [Stone]
	  ,CAST(REPLACE([Gold],',','') AS INT) AS [Gold]
	  ,CAST(REPLACE([Trade_Profit],',','') AS INT) AS [Trade_Profit]
	  ,CAST(REPLACE([Tribute_Received],',','') AS INT) AS [Tribute_Received]
	  ,CAST(REPLACE([Tribute_Sent],',','') AS INT) AS [Tribute_Sent]
	  ,CASE WHEN [Feudal_Time] = 'n/a' THEN NULL ELSE LTRIM(DATEDIFF(MINUTE, 0, TRY_CONVERT(TIME(0),[Feudal_Time], 105))) END AS [Feudal_Time]
	  ,CASE WHEN [Castle_Time] = 'n/a' THEN NULL ELSE LTRIM(DATEDIFF(MINUTE, 0, TRY_CONVERT(TIME(0),[Castle_Time], 105))) END AS [Castle_Time]
	  ,CASE WHEN [Imperial_Time] = 'n/a' THEN NULL ELSE LTRIM(DATEDIFF(MINUTE, 0, TRY_CONVERT(TIME(0),[Imperial_Time], 105))) END AS [Imperial_Time]
      ,ROUND(CAST(REPLACE([Map_Explored],'%','') AS FLOAT)/100,4) AS [Map_Explored]
      ,CAST([Research_Count] AS INT) AS [Research_Count]
      ,ROUND(CAST(REPLACE([Research_Percent],'%','') AS FLOAT)/100,4) AS [Research_Percent]
	  ,CAST(REPLACE([Total_Wonders],',','') AS INT) AS [Total_Wonders]
	  ,CAST(REPLACE([Total_Castles],',','') AS INT) AS [Total_Castles]
	  ,CAST(REPLACE([Relics_Captured],',','') AS INT) AS [Relics_Captured]
	  ,CAST(REPLACE([Relic_Gold],',','') AS INT) AS [Relic_Gold]
	  ,CAST(REPLACE([Villager_High],',','') AS INT) AS [Villager_High]
FROM [AOE2_VOOBLY].[dbo].[RAW_MATCH_DATA]
